### ISSUE TITLE
MMScrapsInSidebarState.m line 221 [scrapIsAddedToSidebar]

### ISSUE THREAD

**Issue by adamwulf-crashlytics** [adamwulf/loose-leaf#1523]
#### in -[MMScrapsInSidebarState scrapIsAddedToSidebar:]
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/milestonemade/ios/apps/com.milestonemade.looseleaf/issues/55f61ecdf5d3a7f76bffd75d](https://fabric.io/milestonemade/ios/apps/com.milestonemade.looseleaf/issues/55f61ecdf5d3a7f76bffd75d)

**Comment by adamwulf** [comment]
seen this in 3.0.1, reopening
