### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by TGWC** [adamwulf/loose-leaf#1735]
I followed all steps but I get error when compiling

ld: 18 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TGWC** [comment]
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMAppDelegate.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMMemoryManager.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafViewController.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMClonePaperStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMButtonToolbarView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMCloudKitImportExportView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMMemoryProfileView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMEditablePaperStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMPanAndPinchScrapGestureRecognizer.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMListPaperStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMTouchVelocityGestureRecognizer.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMDebugStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMPagesInBezelContainerView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMTutorialStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMListSidebarStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMFullWidthListButton.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMScrapPaperStackView.o
duplicate symbol _SidebarButton in:
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMLooseLeafView.o
    /Users/TGWC/Library/Developer/Xcode/DerivedData/LooseLeaf-cfrudrvzdyqrrkewqyiiqpalvmpn/Build/Intermediates/LooseLeaf.build/Debug-iphonesimulator/LooseLeaf.build/Objects-normal/x86_64/MMCollapsableStackView.o
ld: 18 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by adamwulf** [comment]
hrm - very strange.  I just re-tested the build w/ a clean clone, and it compiled to simulator and device just fine. made our Xcode versions are different?

I'm on Xcode Version 8.2.1 (8C1002) and my loose leaf clone is on master at 9884c2bb. Is this the same for you as well?

**Comment by TGWC** [comment]
Hi,

I get the same error. Can you zip your project folder and share it here via https://wetransfer.com ? Thanks

**Comment by adamwulf** [comment]
I'd rather find out what's going on and fix it, so that others don't get stuck on this too.

what are the results when you type:

`git status`

and

`git log -n 1`

on the command line in the loose leaf source directory?

**Comment by TGWC** [comment]
I got it to work, thanks a lot! Another thing, how can I add a crayon texture ? It's easy ?

**Comment by adamwulf** [comment]
Yep - new textures are pretty straightforward. Look at Highlighter.m and JotHighlighterBrushTexture.m as examples
