### ISSUE TITLE
Getting started troubles

### ISSUE THREAD

**Issue by saiedg** [adamwulf/loose-leaf#1834]
I used Xcode to setup the git repo. When I open terminal I: 
cd loose-leaf

Then when I:
git submodule update --recursive --init

I get this error for every submodule:
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:AFNetworking/AFNetworking.git' into submodule path failed
Failed to clone 'Submodules/AFNetworking' a second time, aborting

Please help me with this error.

**Comment by adamwulf** [comment]
It seems from [this similar error](https://github.com/jakubroztocil/cloudtunes/issues/23) that the solution is to setup your ssh key in GitHub settings:

> Just copy your /root/.ssh/id_rsa.pub content as new github SSH key (https://github.com/settings/ssh).
> 
> If you does't have id_rsa.pub, just create it with command ssh-keygen -t rsa

**Comment by saiedg** [comment]
Worked!! Thank you so much!
