### ISSUE TITLE
Mixpanel submodule failed to be cloned

### ISSUE THREAD

**Issue by kloned** [adamwulf/loose-leaf#1867]
**Problem**
Mixpanel submodule can't be fetched anymore due to its non existent commit hash.

**Explanation**
An attempt to get all the submodules by `git submodule update --recursive --init` ends up with error:
```
.....
error: Server does not allow request for unadvertised object 578cfe1f2b143265c86477a3cb787b79ad50a8a4
Fetched in submodule path 'Submodules/mixpanel', but it did not contain 578cfe1f2b143265c86477a3cb787b79ad50a8a4. Direct fetching of that commit failed.
```

This hash is specified in **loose-leaf** main directory git's object database for mixpanel submodule.
It's also explicitly displayed by github in Submodules [directory](https://github.com/adamwulf/loose-leaf/tree/master/Submodules):
<img width="240" alt="Screenshot 2019-05-24 at 22 20 50" src="https://user-images.githubusercontent.com/7922619/58354591-3a3da200-7e72-11e9-97e6-141e0fd03f82.png">

[Mixpanel](https://github.com/mixpanel/mixpanel-iphone) repository doesn't contain the commit with such hash anymore. 
It could be due some clean-up or rebasing work on their side.

I've tried to clone mixpanel manually in its Submodule directory. However the latest commit from its master branch results in loose-leaf linkage errors.

**Comment by adamwulf** [comment]
try using the remote https://github.com/adamwulf/mixpanel-iphone

it's likely i didn't properly update the remote when i added that fork. (it should probably work if you just set mixpanel to whatever their latest stable is as well, in theory)

**Comment by kloned** [comment]
Just did a clean test with this changes, now it works as expected
