### ISSUE TITLE
update photo manager code so that i can add in default photo albums easier w/o relying on alasset

### ISSUE THREAD

**Issue by adamwulf** [adamwulf/loose-leaf#839]
this is a coding task, not a bug. right now all photo albums rely on the ALAsset class to display photos. instead, i should make this a bit more generic so i can easily swap in other photo providers

**Comment by jjuliano** [comment]
Hi @adamwulf, I tried adding photos to the BundledPhotos folder, however, it's not previewing and cannot be selected. Am I missing some implementation?

**Comment by adamwulf** [comment]
@jjuliano  I just pushed an update to `master` that shows how to do it. The trick is to add a BundledPhotos directory to your source as a folder /reference/, then make sure that folder is copied into the Resources folder during the build phase. that folder also needs subfolders for any 'albums' you want to add. My sample commit added an `BundledPhotos/unsplash` folder with a few sample photos.
